// src/components/FooterComponent.vue
<template>
    <footer>
        <div class="footer-content">
        <p>&copy; 2025 Vue Musica. Todos los derechos reservados.</p>
        <p>Desarrollado por Nicolas Oxovi</p>
        </div>
    </footer>
</template>
<script>
export default {
    name: 'FooterComponent',
}
</script>
<style scoped>
footer {
    background-color: #0a063a;
    color: white;
    text-align: center;
    padding: 15px 0;
    position: relative;
    border-top: 2px solid rgb(10, 6, 58);
}
</style>

// src/components/FooterComponent.jsx
const FooterComponent = () => {
  return (
    <footer className="bg-[#0a063a] text-white text-center py-4 relative border-t-2 border-brand-blue mt-8">
      <div className="flex flex-col items-center justify-center gap-1">
        <p className="m-0">Nicolas Oxovi</p>
        <p className="m-0">Aplicaciones Web</p>
      </div>
    </footer>
  )
}

export default FooterComponent
