// src/components/HeaderComponent.vue
<template>
  <header>
    <div class="logo-titulo">
      <img src="../images/imagenLogo.png" alt="Imagen del logo" />
      <h2>Adivina la Canción</h2>
    </div>
    <nav>
      <ul>
        <li><router-link to="/">Inicio</router-link></li>
        <li><router-link to="/jugar">Jugar</router-link></li>
        <li><router-link to="/ranking">Ranking</router-link></li>
      </ul>
    </nav>
  </header>
</template>
<script>
export default {
  name: 'HeaderComponent',
}
</script>
<style scoped>
img {
  position: relative;
  width: 70px;
  margin-right: 15px;
}

header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: #ffffff;
  padding: 10px 20px;
  color: white;
  border-bottom: 2px solid rgb(10, 6, 58);
}

.logo-titulo {
  display: flex;
  align-items: center;
}

ul {
  list-style-type: none;
  display: flex;
}

h2 {
  color: rgb(10, 6, 58);
}

a {
  font-size: 18px;
  border: 1px solid rgb(10, 6, 58);
  padding: 8px 12px;
  border-radius: 8px;
  text-decoration: none;
  margin-left: 20px;
  color: rgb(10, 6, 58);
}

a:hover {
  background-color: rgb(10, 6, 58);
  color: #ffffff;
}

li:last-child a {
  margin-right: 0;
}
</style>

// src/components/HeaderComponent.jsx
import { Link } from 'react-router-dom'
import logoImg from '../images/imagenLogo.png'

const HeaderComponent = () => {
  return (
    <header className="flex justify-between items-center bg-white py-2.5 px-5 border-b-2 border-brand-blue">
      <div className="flex items-center">
        <img src={logoImg} alt="Imagen del logo" className="relative w-[70px] mr-[15px]" />
        <h2 className="text-brand-blue m-0 text-2xl font-bold">Adivina la Canción</h2>
      </div>
      <nav>
        <ul className="list-none flex m-0 p-0">
          <li><Link to="/" className="text-[18px] border border-brand-blue py-2 px-3 rounded-lg no-underline ml-5 text-brand-blue hover:bg-brand-blue hover:text-white transition-colors font-semibold">Inicio</Link></li>
          <li><Link to="/jugar" className="text-[18px] border border-brand-blue py-2 px-3 rounded-lg no-underline ml-5 text-brand-blue hover:bg-brand-blue hover:text-white transition-colors font-semibold">Jugar</Link></li>
          <li><Link to="/ranking" className="text-[18px] border border-brand-blue py-2 px-3 rounded-lg no-underline ml-5 text-brand-blue hover:bg-brand-blue hover:text-white transition-colors font-semibold">Ranking</Link></li>
          <li><Link to="/contacto" className="text-[18px] border border-brand-blue py-2 px-3 rounded-lg no-underline ml-5 text-brand-blue hover:bg-brand-blue hover:text-white transition-colors font-semibold">Contacto</Link></li>
          <li><Link to="/auditoria" className="text-[18px] border border-brand-blue py-2 px-3 rounded-lg no-underline ml-5 text-brand-blue hover:bg-brand-blue hover:text-white transition-colors font-semibold">Auditoría</Link></li>
        </ul>
      </nav>
    </header>
  )
}

export default HeaderComponent
